<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->

<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>

<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>

<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>

<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED
>

<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose ( optional | mandatory | development ) "optional"
>

<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!-- bldFile  may someday be removed in favour of mrp -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition schema="2.0.1" name="Graphics">
<systemModel>
<layer name="anonymous">
<block name="graphics" long-name="Graphics" levels="adaptation engines internal-adaptations device-interface internal-utils app-if">
<collection name="graphics_plat" long-name="Graphics Platform Interfaces" level="shai">
<component name="guestvideodriver_api" long-name="Guest Video Driver API" introduced="^4" class="api">
<unit bldFile="graphics_plat/guestvideodriver_api/group"/>
</component>
<component name="surfacemanager_api" long-name="Surface Manager API" introduced="^3" class="api">
<unit bldFile="graphics_plat/surfacemanager_api/group"/>
</component>
</collection>
<collection name="graphicshwdrivers" long-name="Graphics Hardware Drivers" level="adaptation">
<!-- displayldd to be moved here -->
<component name="surfacemgr" long-name="Surface Manager" introduced="^3" purpose="optional">
<unit bldFile="graphicshwdrivers/surfacemgr/group" mrp="os/deviceplatformrelease/foundation_system/system_model/graphicshwdrivers/surfacemgr/group/graphics_surfacemanager.mrp"/>
</component>
</collection>
</block>
</layer>
</systemModel>
</SystemDefinition>
